### ISSUE TITLE
Flickering when drawing layers individually

### ISSUE THREAD

**Issue by somnambulism-** [fallahn/sfml-tmxloader#17]
Calling mapLoader.Draw(window, layerIndex) on map layers individually can cause layers to flicker / phase in and out, depending on the view position. This doesn't happen when window.draw(mapLoader) is called.

Please see the following video for more details
https://www.youtube.com/watch?v=mPYO3ZDr3nU

**Comment by fallahn** [comment]
merged this with issue #28
