### ISSUE TITLE
VS2013 Project error not generate .libs

### ISSUE THREAD

**Issue by Hevedy** [fallahn/sfml-tmxloader#26]
I selected in cmake shared libs dlls, at build the vs project, but at compile, the examples and drop an error of no find .lib files of tmx-loader or pugi (in release mode x32)

pugi.vcxproj -> E:\A\Software\C_C++\sfml-tmxloader-master\build\Release\pugi.dll
Error	2	error LNK1181: cannot open input file 'Release\pugi.lib'	E:\A\Software\C_C++\sfml-tmxloader-master\build\LINK	tmx-loader

Error	4	error LNK1181: cannot open input file 'Release\tmx-loader.lib'	E:\A\Software\C_C++\sfml-tmxloader-master\build\LINK	QuadTree

**Comment by fallahn** [comment]
neither pugi nor tmx were designed to be exported as dlls, and no functions are exported in code. Because of this VC will create dll files but no libs. Just add the cpp files to your project (except the box2D file if you're not using box2D) so the map loader is compiled as part of your executable.

**Comment by fallahn** [comment]
This is fixed in the next branch (for version 2.0.0)
