### ISSUE TITLE
Please add functions to return map tiles' width and height

### ISSUE THREAD

**Issue by Mars999** [fallahn/sfml-tmxloader#29]
//Get tile width
		sf::Uint16 GetTileWidth();
		//Get tile height
		sf::Uint16 GetTileHeight();

sf::Uint16 MapLoader::GetTileWidth()
{
	return m_tileWidth;
}

sf::Uint16 MapLoader::GetTileHeight()
{
	return m_tileHeight;
}

**Comment by fallahn** [comment]
or even simpler (aside from the fact those functions should be const):
````
sf::vector2u GetTileSize() const { return {m_tileWidth, m_tileHeight}; }
````
feel free to submit a pull request :)

**Comment by Mars999** [comment]
sorry I have no idea on how to get a pull request please update it for me... sorry

thanks, just never used this before to do that I always just find bugs and inform them. I should learn this stuff more... no time right now... :(

**Comment by fallahn** [comment]
Click the fork button to create your own fork of the repo on github

Clone your fork to your computer and modify the source code / make any changes. If this is enough for you then that's all you need to do for a modified version.

If you feel your changes can contribute to the original, push any commits to your fork on github. At the top right corner of the fork's page there's a link to Pull Request. Click it to submit your changes to the original repo.

https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/using-pull-requests/#fork--pull

**Comment by Mars999** [comment]
Oops delete other posting... 

also I guess it's uploaded? Please check to see if my changes made it?

Thanks! Great lib by the way!!!

**Comment by fallahn** [comment]
I can see your fork, but you haven't pushed any changes to it yet. You need to commit your changes locally, then push them to your fork.

https://help.github.com/articles/pushing-to-a-remote/

When you can see your changes on the github page for your fork, you can then submit them as a pull request.

Thanks for making the effort to help out :)
