### ISSUE TITLE
Please add a Default Constructor that takes no addSearchPath() in Map Loader Class

### ISSUE THREAD

**Issue by Mars999** [fallahn/sfml-tmxloader#33]
I would like to see this added to map Loader

class MapLoader final : public sf::Drawable, private sf::NonCopyable
	{
	public:
		MapLoader();
		MapLoader(const std::string& mapDirectory);

in maplaoderpublic.cpp

//ctor
MapLoader::MapLoader()
	: m_width(1u),
	m_height(1u),
	m_tileWidth(1u),
	m_tileHeight(1u),
	m_tileRatio(1.f),
	m_mapLoaded(false),
	m_quadTreeAvailable(false),
	m_failedImage(false)
{
	//reserve some space to help reduce reallocations
	m_layers.reserve(10);
}
MapLoader::MapLoader(const std::string& mapDirectory)
	: m_width			(1u),
	m_height			(1u),
	m_tileWidth			(1u),
	m_tileHeight		(1u),
	m_tileRatio			(1.f),
	m_mapLoaded			(false),
	m_quadTreeAvailable	(false),
	m_failedImage		(false)
{
	//reserve some space to help reduce reallocations
	m_layers.reserve(10);

	AddSearchPath(mapDirectory);
}

**Comment by fallahn** [comment]
If you want to use the map loader as a class member use [member initialisation lists](http://en.cppreference.com/w/cpp/language/initializer_list) like [this](http://hastebin.com/minijiseve.cpp). The fact that there is no default constructor is to enforce required data is supplied to the map loader class.
