### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by Elit3d** [fallahn/sfml-tmxloader#39]
I have a few linker errors (they are here):
http://www.gamedev.net/topic/670937-sfml-tmxloader-issues/

Not sure if I'm supposed to have any .lib files but at the moment I dont. Can't figure out why else it wouldn't be working.

**Comment by fallahn** [comment]
There are two methods: you can either include the cpp files as part of your project (the box2D one is optional, don't include it if you're not using box2D), or you can use the cmake file to create a project for your compiler of choice, and compile that project separately. This will give you a lib file to which you can link your main project.

**Comment by Elit3d** [comment]
https://i.gyazo.com/faeb3a5ab32f8d23509fbbd316db7f6c.png like this?
