### ISSUE TITLE
Laggy and doesn't draw all map?

### ISSUE THREAD

**Issue by Elit3d** [fallahn/sfml-tmxloader#41]
I'm not sure why but the map is laggy and it only loads a portion of the map, here's my code:

```
#include "MapClass.h"

std::vector<sf::FloatRect> mapBounds;
tmx::MapLoader map("maps/");
std::vector<tmx::MapLayer> mapLayers;
sf::Vector2u mapSize;

MapClass::MapClass()
{
}

MapClass::~MapClass()
{
}

void MapClass::loadMap(std::string mapName, sf::RenderWindow &window)
{	
	map.Load(mapName);
	window.draw(map);
}
```
and I am drawing it like so in my main function:

```
map->loadMap("lvl1.tmx", window);
```

here is what it looks like when I run it

https://gyazo.com/79fe4505836707d4a15524f1ae30792a

**Comment by fallahn** [comment]
The first thing which stands out is that you're trying to load the map every frame. You only need to load the map once, then draw it in your loop. Take a look at one of the included examples: https://github.com/fallahn/sfml-tmxloader/blob/master/examples/MapWithQuadTree.cpp

**Comment by Elit3d** [comment]
Ah yes, that makes sense! It's fixed now many thanks!
