### ISSUE TITLE
Only first created layer get rendered

### ISSUE THREAD

**Issue by apocarteres** [fallahn/sfml-tmxloader#45]
Hi, guys! Thanks for your work! 

I started using your loader and faced an issue with rendering multiple layers.
Basically when i add more than one layer

<img width="1131" alt="screen shot 2015-11-12 at 12 14 30 pm" src="https://cloud.githubusercontent.com/assets/3305624/11114648/45d9021e-8937-11e5-9645-d2dab5402746.png">

i see that sfml-txloader keeps rendering only one layer on scene:

<img width="1012" alt="screen shot 2015-11-12 at 12 18 00 pm" src="https://cloud.githubusercontent.com/assets/3305624/11114680/75c865dc-8937-11e5-9dc6-2be9c97b89af.png">

I compiled project with logging and log looks fine either:

```
INFO: Caching image files, please wait...
INFO: Processed isometric_grass_and_water.png
INFO: Processed castle1.png
INFO: Processed ground1.png
INFO: Processed ground2.png
INFO: Processed tree1.png
INFO: Processed tree2.png
INFO: Found standard map layer water
INFO: Found Base64 encoded layer data, decoding...
INFO: Found zlib compressed layer data, decompressing...
INFO: Found standard map layer ground
INFO: Found Base64 encoded layer data, decoding...
INFO: Found zlib compressed layer data, decompressing...
INFO: Found standard map layer building
INFO: Found Base64 encoded layer data, decoding...
INFO: Found zlib compressed layer data, decompressing...
INFO: Found standard map layer road
INFO: Found Base64 encoded layer data, decoding...
INFO: Found zlib compressed layer data, decompressing...
INFO: Found standard map layer tree
INFO: Found Base64 encoded layer data, decoding...
INFO: Found zlib compressed layer data, decompressing...
INFO: Parsed 5 layers.
INFO: Loaded tmx file successfully.
```

Could you please advice how to get all layers be rendered?

Thanks!

**Comment by fallahn** [comment]
Hi, thanks for the feedback. I've just tried the 'IsometricWithConvertCoords' sample in the examples folder with a multi-layered map, and I don't appear to have this problem. Could you possibly try your map with the example code and/or post your drawing code here?

**Comment by apocarteres** [comment]
Hi, thank for fast reply. I tried to use example code with default map shipped with example and it fine, i added new Tile layer and it was drawn well, but i noticed that my map has a bit different setup such that:
my map is 128x128 and objects placed close to map center, so that's why i can't see them :) I actually misunderstood my 2nd screenshot, i basically thought that i see whole map but not only one little peace of it. 

Anyway thanks for your attention and good luck!
