### ISSUE TITLE
Visual Studio Compatability issues

### ISSUE THREAD

**Issue by MossFrog** [fallahn/sfml-tmxloader#51]
I'm having difficulty using your libraries with visual studio 2013, can you possibly add a tutorial to the description or a link on how to integrate your libraries to a visual studio project?

Best Regards.

**Comment by fallahn** [comment]
That's not a bad idea. When I get a few moments I'll update the wiki. For now though you should be able to get on by adding the source files (including pugixml, excluding tmx2box2d if not using box2d) to your project, and linking to zlib. You'll need to build zlib separately, there are a few tutorials out there for that (I'll link them eventually when I update the wiki)

**Comment by MossFrog** [comment]
Thanks man you are the best, If you get a small tutorial up and running I will definitely create an example VS project plus referr links to your libraries. I think my troubles stem at zlib so ill give that some work.

:heart:

**Comment by fallahn** [comment]
Wiki page [here](https://github.com/fallahn/sfml-tmxloader/wiki/Building) :)

**Comment by MossFrog** [comment]
You are the best! I will update my example tonight!
