### ISSUE TITLE
Map objects not of tile size are offset

### ISSUE THREAD

**Issue by Muon** [fallahn/sfml-tmxloader#53]
The offset added with https://github.com/fallahn/sfml-tmxloader/blob/master/src/MapLoaderPrivate.cpp#L916 messes up map object placement, displacing objects down if their images are not tile-sized. Commenting it out fixes it, but I'm not sure if that might break something else.

**Comment by fallahn** [comment]
Thanks for the PR. Will have to double check why I did this in the first place before accepting it though.
