### ISSUE TITLE
Thanks Matt!

### ISSUE THREAD

**Issue by MossFrog** [fallahn/sfml-tmxloader#55]
I followed your guide on the wiki and got everything to work perfectly, I created a demonstration with a portable (machine independent) Visual Studio project/Demo here that can be used as a template for anyone who downloads the project along with a demonstration of how the camera can be used to traverse the TMX maps. Along with that I added a built version of Zlib for the x86 architecture to the project for people who have trouble building it. Thanks for all the help and i would love it if you left a link to the template in your project description ;). 

Best Regards!

https://github.com/MossFrog/Tile_Map

PS: I will add a readme tommorow!

**Comment by fallahn** [comment]
Thanks for the input! You ought to be able to edit the wiki page yourself if you want to add the link. If not I'll add it when I get 5 minutes

**Comment by MossFrog** [comment]
Allright Matt ! I added a small entry to the wiki and added a readme to the project :) ! 
Best Regards MossFrog!

**Comment by fallahn** [comment]
Many thanks :)
