### ISSUE TITLE
No compatibility with AnimatedSprite class?

### ISSUE THREAD

**Issue by Hyrozen** [fallahn/sfml-tmxloader#56]
Hi!
I'm new using TMXLoader, but what an incredible tool ! 
I'm also using AnimatedSprite class : https://github.com/SFML/SFML/wiki/Source%3A-AnimatedSprite
And here is the problem : Whenever I load a" tmx" map and more precisely whenever i draw it, I am no longer able to see my animated sprite on the screen, while in the meantime, I am able to see classics sprites...

Here's my code : 

#include <SFML/Graphics.hpp>
#include <tmx/MapLoader.h>
#include "AnimatedSprite.h"
#include <iostream>

int main()
{
	// setup window
	sf::Vector2i screenDimensions(800, 640);
	sf::RenderWindow window(sf::VideoMode(screenDimensions.x, screenDimensions.y), "TMXLoader");
	window.setFramerateLimit(60);
	sf::View view(window.getDefaultView());

	// load texture (spritesheet)
	sf::Texture texture;
	if (!texture.loadFromFile("ressource/character/walk.png"))
	{
		std::cout << "Failed to load player spritesheet!" << std::endl;
		return 1;
	}

	// set up the animations for all four directions (set spritesheet and push frames)
	Animation walkingAnimationUp;
	walkingAnimationUp.setSpriteSheet(texture);

	Animation walkingAnimationLeft;
	walkingAnimationLeft.setSpriteSheet(texture);

	Animation walkingAnimationDown;
	walkingAnimationDown.setSpriteSheet(texture);

	Animation walkingAnimationRight;
	walkingAnimationRight.setSpriteSheet(texture);

	for (int i = 0; i <= 512; i += 64)
	{
		walkingAnimationUp.addFrame(sf::IntRect(i, 0, 64, 64));
		walkingAnimationLeft.addFrame(sf::IntRect(i, 64, 64, 64));
		walkingAnimationDown.addFrame(sf::IntRect(i, 128, 64, 64));
		walkingAnimationRight.addFrame(sf::IntRect(i, 192, 64, 64));
	}

	Animation* currentAnimation = &walkingAnimationDown;

	// set up AnimatedSprite
	AnimatedSprite animatedSprite(sf::seconds(0.2), true, false);
	animatedSprite.setPosition(sf::Vector2f(screenDimensions / 2));

	tmx::MapLoader ml("ressource/maps");
	ml.Load("prison.tmx");

	sf::Clock frameClock;

	float speed = 100.f;
	bool noKeyWasPressed = true;

	while (window.isOpen())
	{
		sf::Event event;
		while (window.pollEvent(event))
		{
			if (event.type == sf::Event::Closed)
				window.close();
			if (event.type == sf::Event::KeyPressed && event.key.code == sf::Keyboard::Escape)
				window.close();
		}

		sf::Time frameTime = frameClock.restart();

		// if a key was pressed set the correct animation and move correctly
		sf::Vector2f movement(0.f, 0.f);
		if (sf::Keyboard::isKeyPressed(sf::Keyboard::Up))
		{
			currentAnimation = &walkingAnimationUp;
			movement.y -= speed;
			noKeyWasPressed = false;
		}
		if (sf::Keyboard::isKeyPressed(sf::Keyboard::Down))
		{
			currentAnimation = &walkingAnimationDown;
			movement.y += speed;
			noKeyWasPressed = false;
		}
		if (sf::Keyboard::isKeyPressed(sf::Keyboard::Left))
		{
			currentAnimation = &walkingAnimationLeft;
			movement.x -= speed;
			noKeyWasPressed = false;
		}
		if (sf::Keyboard::isKeyPressed(sf::Keyboard::Right))
		{
			currentAnimation = &walkingAnimationRight;
			movement.x += speed;
			noKeyWasPressed = false;
		}
		animatedSprite.play(*currentAnimation);
		animatedSprite.move(movement * frameTime.asSeconds());

		// if no key was pressed stop the animation
		if (noKeyWasPressed)
		{
			animatedSprite.stop();
		}
		noKeyWasPressed = true;

		// update AnimatedSprite
		animatedSprite.update(frameTime);

		// draw
		window.clear();
		window.draw(animatedSprite);
		window.draw(ml);
		window.display();
	}

	return 0;
}

**Comment by fallahn** [comment]
The order in which you draw things is important. In this case you are drawing your sprite first then the map on top of it, which is why you can't see the sprite. In general you should always draw the map first. Have a look on the wiki for the article on z-ordering.

**Comment by Hyrozen** [comment]
I feel so...
Anyways, huge thanks, and again thanks for this incredible tool ! :)
