### ISSUE TITLE
MapObject setVisible ?

### ISSUE THREAD

**Issue by SupaJosh** [fallahn/sfml-tmxloader#57]
Hi,
Since i'm newbie with TmxLoader, I dunno how it is supposed to work but :

    for (auto& layer : layers)
    {
        if (layer.type == tmx::ObjectGroup)
        {
            for (auto& obj : layer.objects)
            {
                if (layer.name == "Collectable")
                {
                    if (obj.Contains(animatedSprite.getPosition()))
	                {
	                   std::cout << "Test";
	                   obj.SetVisible(false);
	                }
                }
            }
        }
    }

I've got the "Test" text in my cmd, but the object is still visible on the map, I really don't know what to think about it?
If anyone has suggestions, it would be really appreciated ! :)

**Comment by fallahn** [comment]
Unfortunately [this is a bug](https://github.com/fallahn/sfml-tmxloader/issues/16)

**Comment by SupaJosh** [comment]
Ok, thanks for your answer ! 
Sounds like I'm gonna have to draw every collectible objects as sprites o.o

**Comment by fallahn** [comment]
fwiw I've pushed the fix of this to the 'next' branch if anyone would like to test it
