### ISSUE TITLE
Animated Tile with Tiled Editor

### ISSUE THREAD

**Issue by OualidH** [fallahn/sfml-tmxloader#62]
Hi everybody,

I was wondering if there is a way to handle animated tiles as follow:
[https://youtu.be/ZwaomOYGuYo?t=15m19s](url)

Because when I add an animation, it is not shown as animated, so I guess it is not handle by the parser.

I've found this issue [https://github.com/fallahn/sfml-tmxloader/issues/6](url)
Unfortunately I've not found in which way Tiled add properties to an animated tile and how to get that property using the parser.

Do you have any idea?

I guess I have to get through all tiles and then check the property, if it is an animated tile, I just have to update the textureRect of the sprite to obtain the animation.

But what is the property for animated tiles?

Any help is appreciate :smile:

**Comment by fallahn** [comment]
Animated tiles were not supported directly by Tiled when I wrote the map parser, so the animation spec was unavailable at the time. Therefore the animation properties are currently not parsed. I do want to support this feature, of course, so it will hopefully make it to version 2 (see the 'next' branch). Contributions are always welcome too! ;)

**Comment by OualidH** [comment]
Ok I will certainly wait for it then ! I tried to add a property to a tile, but I wasn't able to get that property in my code. Is there a reason why it is not possible to get a tile property where it is possible to get an object property?

**Comment by fallahn** [comment]
Mostly [this](https://github.com/fallahn/sfml-tmxloader/blob/master/src/MapLoaderPrivate.cpp#L315) I think :)

**Comment by OualidH** [comment]
Ok thank you for your reply, and thanks for your amazing work ;)
